
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "warUnit.sol";

contract warrior is warUnit {

    constructor(warUnit newWarriorUnit) public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();

        address baseAddr = address(warUnit);
    }

    address private baseAddr;

    uint warriorHP;
    uint warriorShield;
    uint warriorPower;

    function getXP() public override {
        tvm.accept();
        warriorHP = HP;
        baseAddress[baseAddr].warriorHP = warriorHP;
    }

    function getShield() public override {
        tvm.accept();
        warriorShield = Shield;
        baseAddress[baseAddr].warriorShield = warriorShield;
    }

    function getPower() public override {
        tvm.accept();
        warriorPower = Power;
        baseAddress[baseAddr].warriorPower = warriorPower;
    }

    function getAttack(uint power) public override {
        tvm.accept();
        warriorHP = warriorHP + warriorShield - power;
        dead(warriorHP);
    }
}
