
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "warUnit.sol";
import "baseStation.sol";

contract archer is baseStation {

    constructor(baseStation newWArcher) public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
        
        // newWarrior;
    
    }

    uint public archerHP = hitPoint;
    uint archerShield = shield;
    uint archerPower = 3;


    // function getPower() public override returns(uint) {
    //     uint power = 2;
    // }

    function getShield() public override returns(uint) {
        tvm.accept();
        return archerShield;
    }

    function getAttack(uint power) external override {
        tvm.accept();
        archerHP = archerHP + archerShield - power; 
        dead(archerHP);
    }

    function attack(interfaceGameObject enemyAddr) public {
        tvm.accept();
        enemyAddr.getAttack(archerPower);
    }
    
}
