
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "warUnit.sol";
import "baseStation.sol";

contract warrior is warrUnit {

    constructor(baseStation newBaseUnit) public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();

    
    }

 

    uint power = 2;

    // function getXP(address addr) virtual internal override {
        // warUnit[addr].unitShield = 5;
    // }

    function getPower(address baseAddr) virtual public override {
        tvm.accept();
        baseUnit[baseAddr].warUnit[msg.sender].unitPower = power;
    }
}
