
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// import "warUnit.sol";
import "baseStation.sol";

contract warrior is baseStation {

    constructor(baseStation newWarrior) public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
        
        // newWarrior;
    
    }

    uint public warriorHP = hitPoint;
    uint warriorShield = shield;
    uint warriorPower = 2;


    // function getPower() public override returns(uint) {
    //     uint power = 2;
    // }

    function getShield() public override returns(uint) {
        tvm.accept();
        return warriorShield;
    }

    function getAttack(uint power) external override {
        tvm.accept();
        warriorHP = warriorHP + warriorShield - power; 
        dead(warriorHP);
    }

    function attack(interfaceGameObject enemyAddr) public {
        tvm.accept();
        enemyAddr.getAttack(warriorPower);
    }
}
