
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "gameObject.sol";
import "baseStation.sol";

contract warrUnit is gameObject {

    constructor(baseStation newWarUnit) public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();

        // address _baseAddr = newWarUnit;

    }

    uint public baseHP = hitPoint;
    uint public baseShield = 0;


    function attack(interfaceGameObject enemyAddr, uint power) internal {
        tvm.accept();
        enemyAddr.getAttack(power);
    }

    function getAttack(uint power) virtual external override {
        tvm.accept();
        baseHP = baseHP + baseShield - power;
        dead(baseHP);
    }
}